services:
  api:
    container_name: mobile-order-api
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    # プロジェクト作成時はcommandをコメントアウト（コンテナが立ち上がらないため）
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${RAILS_PORT}:3000 # 環境変数から参照
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける設定。
    stdin_open: true
    depends_on:
      - db
  # MySQLの設定
  db:
    container_name: mobile_order_db
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB} # 環境変数から参照
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # 環境変数から参照
      TZ: "Asia/Tokyo"
    ports:
      - "${MYSQL_POOT}:3306" # 環境変数から参照
  minio:
    container_name: mobile-order-minio
    image: minio/minio:latest
    platform: linux/amd64
    volumes:
      - minio:/export:delegated
    networks:
      default:
        aliases:
          - minio.127.0.0.1.nip.io
          - file.minio.127.0.0.1.nip.io
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      ACCESSKEY: ${MINIO_ACCESS_KEY_ID}
      SECRET_KEY: ${MINIO_SECRET_ACCESS_KEY}
    entrypoint: sh
    command: -c 'mkdir -p /export/mobile-order && mkdir -p /export/mobile-order-dev && minio server /export --console-address ":9001"'
volumes:
  minio:
  db-data:
